### ISSUE TITLE
Mosquitto logging permissions

### ISSUE THREAD

**Issue by Dax333** [toke/docker-mosquitto#12]
Running on QNAP Container station.  

docker run -ti --net=host -p 1884:1884 -p 9004:9004 \
    -v /share/Containers/mosquitto-int/config:/mqtt/config:ro \
    -v /share/Containers/mosquitto-int/log:/mqtt/log:rw \
    -v /share/Containers/mosquitto-int/data/:/mqtt/data/ \
    --name mqtt-int -d toke/mosquitto

conf file:
log_dest file /mqtt/log/mosquitto.log

I had to comment out config log path due to error.

[/share/CACHEDEV1_DATA/Containers/mosquitto-int/log] # docker logs mqtt-int
1473191957: Error: Unable to open log file /mqtt/log/mosquitto.log for writing.

In shell I can manually write to /mqtt/log/ with no problem and on the host side the created file or folder is owned by admin.

root@b91c2abe1a34:/mqtt/log# ls -la
total 20
drwxrwxrwx+ 3 root      root      4096 Sep  6 20:03 .
drwxr-xr-x  5 mosquitto mosquitto 4096 Sep  2 15:18 ..
drwxrwx---+ 2 root      root      4096 Sep  6 20:03 test

[/share/CACHEDEV1_DATA/Containers/mosquitto-int/log] # ls -la
drwxrwxrwx    3 admin    administ      4096 Sep  6 13:03 ./
drwxrwxrwx    5 admin    administ      4096 Sep  1 18:47 ../
drwxrwx---    2 admin    administ      4096 Sep  6 13:03 test/

I am somewhat new to this so am I missing something obvious?

**Comment by toke** [comment]
I tried to reproduce this behaviour. I could not. Your examples looks good to me. I'm a little bit puzzled.

I used the following configuration.

```bash
mkdir /tmp/issue12data/
mkdir /tmp/issue12data/{data,log,config}
chmod 777 /tmp/issue12data/{data,log,config}
```

Placed the following in `/tmp/issue12data/config/mosquitto.conf`:

```
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /mqtt/data/

user mosquitto

port 1883

log_dest file /mqtt/log/mosquitto.log
```

Started:

```bash
docker run -ti --net=host -p 1883:1883 -p 9004:9004 \
-v /tmp/issue12data/data/:/mqtt/data/:rw \
-v /tmp/issue12data/logs:/mqtt/log:rw \
-v /tmp/issue12data/config/:/mqtt/config:ro \
 --name mqtt-int -d toke/mosquitto
```

and I get

```
$ ls -lsan logs/mosquitto.log 
4 -rw-r--r-- 1 104 107 1251 Sep  6 22:39 logs/mosquitto.log
```

**Comment by Dax333** [comment]
I don't know if it's a UID mismatch problem with QNAP's implementation of docker.  I'll have to test on another platform.  I know mosquitto is being run as the user mosquitto but i don't know how to test file creation as that user in the container.  

I know I'm flailing but this is what I've found.
https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by Dax333** [comment]
So it turns out the docker host volume needs to have the same UID as the non root user in the container.  The user mosquitto with a UID of 104 cannot write to the host filesystem unless you set the UID of /tmp/issue12data/logs to 104.  This seems to be a common gripe with docker containers, but I'm sure it depends on which host you are running it on.

**Comment by toke** [comment]
Thanks for the feedback

**Comment by depperson** [comment]
@Dax333 sorry to bother you but how did you solve this for QNAP container station?  Did you need to change the UID on the QNAP fs side?

**Comment by akulubala** [comment]
any quick solution about this?

**Comment by MartinMuzatko** [comment]
If anyone else runs over this issue: Setting `chmod o+w mosquitto/log/mosquitt.log` fixed the problem for me.
Otherwise for a **real** fix: Your `mosquitto.log` file on your host must have the same group ID (not group name) that corresponds to the group ID of mosquitto on the container.

**Comment by akpuggy** [comment]
> If anyone else runs over this issue: Setting `chmod o+w mosquitto/log/mosquitt.log` fixed the problem for me.
> Otherwise for a **real** fix: Your `mosquitto.log` file on your host must have the same group ID (not group name) that corresponds to the group ID of mosquitto on the container.

Any suggestion for how to find the group ID of the mosquitto container?

**Comment by jtomasrl** [comment]
I'm running into the same problem

```
services:
  mqtt:
    container_name: mqtt
    user: 1002:1002
```

`uid=1002(mosquitto) gid=1002(mosquitto) groups=1002(mosquitto)`

`-rwxr-xrwx 1 mosquitto mosquitto 1 May  5 11:29 mosquitto.log`
