### ISSUE TITLE
Removing dependency on Q?

### ISSUE THREAD

**Issue by cefn** [toke/docker-mosquitto#4]
Given the only feature of Q you use is ```q.defer()``` is there any chance of removing this dependency?

Mozilla provides an alternative implementation.
https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred

**Comment by toke** [comment]
This project has no Dependency to Q and does not have Javascript at all. So I think Issue is wrong here.

**Comment by cefn** [comment]
Copy paste error with two issues for similarly named project. Was meant to be in dockermachine sorry.
