### ISSUE TITLE
Failure to write to folder when loaded using 'run' instructions.

### ISSUE THREAD

**Issue by cefn** [toke/docker-mosquitto#5]
Hi there. Thanks for making it super-easy for me to configure docker images with Mosquitto. In the end I'll be creating my own images, but this provides a really valuable starting point.

I find the following issue when launching and closing the image, though. It appears not to be able to write to the proper location (although it's loading, I guess the relevant folders are read only). The broker comes up and is functional, however.

This is following the simple 'run' instructions at https://github.com/toke/docker-mosquitto

I guess changing the conf to not employ persistence or logging would eliminate these.

```
dyn-10-32-103-135:~ cefn$ docker run -ti -p 1883:1883 -p 9001:9001 toke/mosquitto
1457349224: Error: Unable to open log file /mqtt/log/mosquitto.log for writing.
1457349224: mosquitto version 1.4.8 (build date Sun, 14 Feb 2016 15:06:55 +0000) starting
1457349224: Config loaded from /mqtt/config/mosquitto.conf.
1457349224: Opening websockets listen socket on port 9001.
1457349224: Opening ipv4 listen socket on port 1883.
1457349224: Opening ipv6 listen socket on port 1883.
^C1457349239: mosquitto version 1.4.8 terminating
1457349239: Saving in-memory database to /mqtt/data/mosquitto.db.
1457349239: Error saving in-memory database, unable to open /mqtt/data/mosquitto.db.new for writing.
1457349239: Error: Permission denied.
```

**Comment by toke** [comment]
Thanks for reporting this!
Since I don't propose building stateful images in this way I did not tested this behaviour, which was wrong I guess ;-)

The Database can now be written as it is configured.
