### ISSUE TITLE
Consider adding the Mosquitto repo key to the build context

### ISSUE THREAD

**Issue by stefan2904** [toke/docker-mosquitto#9]
At the moment, Mosquitto's APT repo key is downloaded from https://repo.mosquitto.org/debian/mosquitto-repo.gpg.key while building the docker image.

I suggest adding the verified key to docker's build context (to this git repo) and copying it into the image during build to mitigate possible security issues during build (in which the key is not verified).

**Comment by toke** [comment]
Thanks for this issue, great catch.
I used another trick used by the tor project by importing the key and exporting it again with the fingerprint.

**Comment by toke** [comment]
Fingerprint is checked.

**Comment by stefan2904** [comment]
thanks a lot!
